/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as KontaktinformationerImport } from './routes/kontaktinformationer'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const KontaktinformationerRoute = KontaktinformationerImport.update({
  id: '/kontaktinformationer',
  path: '/kontaktinformationer',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/kontaktinformationer': {
      id: '/kontaktinformationer'
      path: '/kontaktinformationer'
      fullPath: '/kontaktinformationer'
      preLoaderRoute: typeof KontaktinformationerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontaktinformationer': typeof KontaktinformationerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontaktinformationer': typeof KontaktinformationerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/kontaktinformationer': typeof KontaktinformationerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kontaktinformationer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontaktinformationer'
  id: '__root__' | '/' | '/kontaktinformationer'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktinformationerRoute: typeof KontaktinformationerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktinformationerRoute: KontaktinformationerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/kontaktinformationer"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/kontaktinformationer": {
      "filePath": "kontaktinformationer.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
