/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PersonoplysningerImport } from './routes/personoplysninger'
import { Route as OpretLoginImport } from './routes/opret-login'
import { Route as KontaktinformationerImport } from './routes/kontaktinformationer'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const PersonoplysningerRoute = PersonoplysningerImport.update({
  id: '/personoplysninger',
  path: '/personoplysninger',
  getParentRoute: () => rootRoute,
} as any)

const OpretLoginRoute = OpretLoginImport.update({
  id: '/opret-login',
  path: '/opret-login',
  getParentRoute: () => rootRoute,
} as any)

const KontaktinformationerRoute = KontaktinformationerImport.update({
  id: '/kontaktinformationer',
  path: '/kontaktinformationer',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/kontaktinformationer': {
      id: '/kontaktinformationer'
      path: '/kontaktinformationer'
      fullPath: '/kontaktinformationer'
      preLoaderRoute: typeof KontaktinformationerImport
      parentRoute: typeof rootRoute
    }
    '/opret-login': {
      id: '/opret-login'
      path: '/opret-login'
      fullPath: '/opret-login'
      preLoaderRoute: typeof OpretLoginImport
      parentRoute: typeof rootRoute
    }
    '/personoplysninger': {
      id: '/personoplysninger'
      path: '/personoplysninger'
      fullPath: '/personoplysninger'
      preLoaderRoute: typeof PersonoplysningerImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kontaktinformationer': typeof KontaktinformationerRoute
  '/opret-login': typeof OpretLoginRoute
  '/personoplysninger': typeof PersonoplysningerRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kontaktinformationer': typeof KontaktinformationerRoute
  '/opret-login': typeof OpretLoginRoute
  '/personoplysninger': typeof PersonoplysningerRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/kontaktinformationer': typeof KontaktinformationerRoute
  '/opret-login': typeof OpretLoginRoute
  '/personoplysninger': typeof PersonoplysningerRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/kontaktinformationer'
    | '/opret-login'
    | '/personoplysninger'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kontaktinformationer' | '/opret-login' | '/personoplysninger'
  id:
    | '__root__'
    | '/'
    | '/kontaktinformationer'
    | '/opret-login'
    | '/personoplysninger'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KontaktinformationerRoute: typeof KontaktinformationerRoute
  OpretLoginRoute: typeof OpretLoginRoute
  PersonoplysningerRoute: typeof PersonoplysningerRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KontaktinformationerRoute: KontaktinformationerRoute,
  OpretLoginRoute: OpretLoginRoute,
  PersonoplysningerRoute: PersonoplysningerRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/kontaktinformationer",
        "/opret-login",
        "/personoplysninger"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/kontaktinformationer": {
      "filePath": "kontaktinformationer.tsx"
    },
    "/opret-login": {
      "filePath": "opret-login.tsx"
    },
    "/personoplysninger": {
      "filePath": "personoplysninger.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
